services:
  - type: web
    name: php-file-upload
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false